### ISSUE TITLE
Any chance Terminal.env could launch automatically for all terminals? What about in `tasks.json`?

### ISSUE THREAD

**Issue by blakeNaccarato** [HaidarZ/vscode-terminal-dotenv#1]
Thanks for implementing this in VSCode. Is it possible that Terminal.env could launch automatically for all temrinals? What about in `tasks.json`?

**Comment by HaidarZ** [comment]
My pleasure. Actually, as I know, there's no way to do this automatically. Visual Studio Code restricts access to the terminal's internal API and commands. Doing it in tasks.json will behave similarly to my extension.

**Comment by blakeNaccarato** [comment]
Ah, oh well. Sounds like an unavoidable limitation then.

Yes, currently I have my terminal profile configured to import environment variables defined in `.env`. And then in `tasks.json` I never call, say `python` directly, but rather call `python` from the terminal, which also invokes the terminal profile environment loading.

Of course, potential contributors would have to configure their machines similarly to benefit from custom environment loading like the above. Your extension cuts out some of that headache for contributors, in that case.
